name: dsvl

//TCP
server:
  port: 8080

node:
  port: 45555

bootstrap-server:
  address: 127.0.0.1
  port: 55555

logging:
  level:
    com.dsvl: debug

spring:
  h2:
    console:
      enabled: true
      path: /h2
    datasource:
      url: jdbc:h2:mem:dsvl
      #      url: jdbc:h2:file:~/db/dsvl
      username: sa
      password:
      driver-class-name: org.h2.Driver